name: contact_manager
version: 1.0.0+1
description: Contact Manager
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  get: 4.6.1
  cupertino_icons: 1.0.4
  animated_splash_screen: 1.1.0
  flutter_spinkit: 5.1.0
  contacts_service: 0.6.3
  google_fonts: 2.3.0
  permission_handler: 6.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

